services:
  - type: web
    name: dealsbyak-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: WEBHOOK_DOMAIN
        fromSecret: WEBHOOK_DOMAIN

  - type: worker
    name: dealsbyak-userbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python userbot.py
    envVars:
      - key: API_ID
        fromSecret: API_ID
      - key: API_HASH
        fromSecret: API_HASH
